[package]
name = "generate-bindings"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4.3", features = ["derive"] }
serde = "1.0"

typescript-type-def = "0.5"

backend = { path = "../backend" }
