[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "z"

[workspace]
members = [
  "crates/backend",
  "crates/browser",
  "crates/generate-bindings",
  "crates/solang",
]
default-members = ["crates/browser"]
resolver = "1"
