version: "3.8"
services:
  playground:
    image: salaheldin18/solang-playground-amd64:latest
    container_name: playground
    restart: always
    volumes:
      - /tmp:/tmp
    ports:
      - "9000:9000"
      - "3000:3000"  # Expose Next.js port
    environment:
      - DOCKER_ENV=true
    runtime: sysbox-runc
