[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.deps]
script = '''
cargo install wasm-bindgen-cli
npm install
'''

[tasks.build-server]
script = '''
cargo build --release --target wasm32-unknown-unknown
wasm-bindgen --out-dir ./packages/app/assets/wasm --target web --typescript ./target/wasm32-unknown-unknown/release/demo_lsp_browser.wasm
'''

[tasks.build-bindings]
script = '''
cargo run -p generate-bindings -- --target $(pwd)/packages/_generated/commontypes/src
'''

[tasks.build-app]
script = '''
npm run build --workspace=packages/app
'''

[tasks.build]
dependencies = ["build-server", "build-bindings", "build-app"]

[tasks.clean-server]
script = '''
cargo clean
'''

[tasks.clean-bindings]
script = '''
rm -rf packages/_generated/commontypes/src
'''

[tasks.clean-app]
script = '''
rm -rf packages/app/dist
rm -rf packages/app/assets/wasm
'''

[tasks.clean]
dependencies = ["clean-server", "clean-app"]

[tasks.format]
script = '''
cargo +nightly fmt --all
'''

[tasks.run]
script = '''
cargo run -p backend -- --frontend_folder packages/app/dist --port 9000
'''

[tasks.test]
command = "cargo"
args = ["test", "--target", "x86_64-unknown-linux-gnu"]
